spring.profiles.active=dev

spring.application.name=train
server.port=8080

logging.level.root=DEBUG

# Logging configuration
logging.file.name=logs/train.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.file.path=logs
logging.file.max-size=10MB

# Spring Boot Actuator configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Info about the application
info.app.name=Train Application
info.app.description=This is a sample Spring Boot application for managing train information.
info.app.version=Training 0.1

# Database configuration (if needed)
spring.datasource.url=jdbc:postgresql://localhost:5433/train_db
spring.datasource.username=postgres
spring.datasource.password=zerodd
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

# Lazy initialization of beans
# spring.main.lazy-initialization=true

# Spring Security configuration (if needed)
# spring.security.user.name=admin
# spring.security.user.password=admin123

# Custom properties for the application
message= Training Spring Boot Application is running!
name=Frank
