spring.profiles.active=prod

spring.application.name=${APP_NAME:train}
server.port=${PORT:8080}

logging.level.root=ERROR

# Logging configuration PROD
logging.file.name=${LOG_FILE:logs/train.log}
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.file.path=${LOG_PATH:logs}
logging.file.max-size=${LOG_MAX_SIZE:10MB}

# Spring Boot Actuator configuration for PROD
management.endpoints.web.exposure.include=health,info

# Info about the application
info.app.name=${APP_NAME:Train Application}
info.app.description=${APP_DESCRIPTION:This is a sample Spring Boot application for managing train information.}
info.app.version=${APP_VERSION:Training 0.1}

# Database configuration (if needed)
spring.datasource.url=${DB_URI:jdbc:postgresql://localhost:5433/train_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:zerodd}
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

# Lazy initialization of beans
# spring.main.lazy-initialization=true

# Spring Security configuration (if needed)
# spring.security.user.name=admin
# spring.security.user.password=admin123

# Custom properties for the application
message=Training Spring Boot Application is running!
username=Frank

# Additional production-specific properties can be added here
spring.security.username=${SECURITY_USERNAME:admin}
spring.security.password=${SECURITY_PASSWORD:admin123}
